In [23]:
import os
import re
import numpy as np
import pandas as pd

In [24]:
path = '/Users/sydneymeier/Downloads/Data/'

## Get submissions as list of lists

In [32]:
submissions = []
keys = []
num_sets = []
files = os.listdir(path)
items = list(range(107))
for file in files:
    x = open(path + file)
    raw = x.readlines()
    key = []
    num_set = []
    for i in items[0::3]:
        val = ''.join(filter(str.isdigit, raw[i]))
        val2 = int(12/(raw[i].count(" ")+1))
        key.append(val)
        num_set.append(val2)
    keys.append(key)
    num_sets.append(num_set)
    answer = []
    for i in items[1::3]:
        val = ''.join(filter(str.isdigit, raw[i]))
        while len(val) < 12:
            val = val+'-' #add empty cells if the answer is too short
        answer.append(val) 
    submissions.append(answer)
    x.close()

In [33]:
accuracy = []
for j in range(len(submissions)):
    key = keys[j]
    ans = submissions[j]
    
    correct_list = []
    for ind in range(36):
        correct = 0
        key_val = key[ind]
        ans_val = ans[ind]
        for k in range(12):
            if key_val[k] == ans_val[k]:
                correct += 1
        correct_list.append(correct)
    accuracy.append(correct_list)
    #.append([np.average(correct_list[0:12]), np.average(correct_list[12:24]), np.average(correct_list[24:])])


In [46]:
accuracy = np.array(accuracy)
print(accuracy[:,:12])
print(np.mean(accuracy[:,:12],axis=1))

[[ 1  4  7  9  4  5  7  5  4  8  3  9]
 [ 6  7  8  4  9  4  9  6  4  4 12  7]
 [ 3  6  5  9  4  3  8 12  4 12  4  8]
 [ 4 11 11 12 12  7 12 11 12 12 10  7]
 [12 12 12 10 11 11  7 12 12 12 10 12]
 [ 2  3  9  9  8  8  8 10  6  6  8  8]
 [ 3 10  8  8  8  9  2  6  5  8  3  8]
 [12  7 12 12 12 11 12 12 11 12 12 12]
 [ 5  8  5  8  7  7  2  6  9  8  8  8]
 [ 6  8  9  8  6  9  8  8  9  4  6  8]
 [12 11 12 12  9 12 12  9 12  9  8 12]
 [ 6  4  4  6  8  6  3  6  6  7  8 11]
 [ 5 11 12 10 10 12 10  7  6  8 10  9]
 [12  8 10  1  3 10  9 10  7 12  6 10]]
[ 5.5         6.66666667  6.5        10.08333333 11.08333333  7.08333333
  6.5        11.41666667  6.75        7.41666667 10.83333333  6.25
  9.16666667  8.16666667]


In [56]:
experiment1 = pd.DataFrame(zip(np.mean(accuracy[:,:12],axis=1),np.std(accuracy[:,:12],axis=1)), columns=["Mean Correct","Standard Deviation"])
experiment2 = pd.DataFrame(zip(np.mean(accuracy[:,12:24],axis=1),np.std(accuracy[:,12:24],axis=1)), columns=["Mean Correct","Standard Deviation"])
experiment3 = pd.DataFrame(zip(np.mean(accuracy[:,24:],axis=1),np.std(accuracy[:,24:],axis=1)), columns=["Mean Correct","Standard Deviation"])
experiment1.mean()


Mean Correct          8.10119
Standard Deviation    2.17965
dtype: float64

In [60]:
pd.DataFrame(zip(accuracy[0],num_sets[0]),columns=["Num Correct","Sets of"])

Num Correct  Sets of
0             1       12
1             4        2
2             7        3
3             9       12
4             4        4
5             5        3
6             7        2
7             5       12
8             4        3
9             8        4
10            3        2
11            9        4
12            8        4
13            6        3
14            5       12
15            6        2
16            5        3
17            4       12
18            8        4
19            3        2
20            8        4
21            5       12
22            4        3
23            8        2
24            4        2
25            4       12
26            3        3
27            2        4
28            6        2
29            3        3
30            4        4
31            6       12
32            1        3
33            5        2
34            7       12
35            6        4

In [70]:

acc12 = []
acc2 = []
acc3 = []
acc4 = []
for j in range(len(submissions)):
    
    A = np.array(list(zip(accuracy[j],num_sets[j])))
    
    sets12 = A[:, [0]][A[:, 1] == 12]
    sets2 = A[:, [0]][A[:, 1] == 2]
    sets3 = A[:, [0]][A[:, 1] == 3]
    sets4 = A[:, [0]][A[:, 1] == 4]
    
    acc12.append(list(A[:, [0]][A[:, 1] == 12].flatten()))
    acc2.append(list(A[:, [0]][A[:, 1] == 2].flatten()))
    acc3.append(list(A[:, [0]][A[:, 1] == 3].flatten()))
    acc4.append(list(A[:, [0]][A[:, 1] == 4].flatten()))


In [72]:
acc12 = np.array(acc12)
acc2 = np.array(acc2)
acc3 = np.array(acc3)
acc4 = np.array(acc4)

In [84]:
acc12

array([[ 1,  9,  5,  5,  4,  5,  4,  6,  7],
       [ 6,  4,  6,  5,  1,  6,  0,  4,  3],
       [ 3,  9, 12,  8, 12,  3,  3,  8,  5],
       [ 4, 12, 11,  9, 12, 12,  7, 12,  8],
       [12, 10, 12, 12, 12, 11, 12, 12, 11],
       [ 2,  9, 10, 11, 12, 12,  9, 11, 10],
       [ 3,  8,  6,  4,  8,  5,  8, 12, 11],
       [12, 12, 12, 12, 12, 10,  8, 12, 12],
       [ 5,  8,  6,  7,  8,  9,  6,  4,  4],
       [ 6,  8,  8,  9,  7,  6,  7,  6,  5],
       [12, 12,  9,  8, 10,  8,  5,  4,  7],
       [ 6,  6,  6,  5,  9,  9,  7,  6,  7],
       [ 5, 10,  7,  6,  9, 12, 12, 10, 10],
       [12,  1, 10,  9, 12, 12, 10,  6,  7]])

In [86]:
experiment1_sets = pd.DataFrame(zip(np.mean(acc12[:,:3],axis=1),np.mean(acc2[:,:3],axis=1),np.mean(acc3[:,:3],axis=1),np.mean(acc4[:,:3],axis=1)),
                                    columns=["Sets of 12 Mean","Sets of 2 Mean","Sets of 3 Mean","Sets of 4 Mean"])
experiment2_sets = pd.DataFrame(zip(np.mean(acc12[:,3:6],axis=1),np.mean(acc2[:,3:6],axis=1),np.mean(acc3[:,3:6],axis=1),np.mean(acc4[:,3:6],axis=1)),
                                    columns=["Sets of 12 Mean","Sets of 2 Mean","Sets of 3 Mean","Sets of 4 Mean"])
experiment3_sets = pd.DataFrame(zip(np.mean(acc12[:,6:],axis=1),np.mean(acc2[:,6:],axis=1),np.mean(acc3[:,6:],axis=1),np.mean(acc4[:,6:],axis=1)),
                                    columns=["Sets of 12 Mean","Sets of 2 Mean","Sets of 3 Mean","Sets of 4 Mean"])
experiment1_sets.mean()

Sets of 12 Mean    7.785714
Sets of 2 Mean     7.785714
Sets of 3 Mean     8.214286
Sets of 4 Mean     8.619048
dtype: float64